name: an_reactive_state
description: "A pure Dart Call-Stack synchronous reactive graph engine. Features unified lazy evaluation, dual-buffered dynamic graph diffing, equality guards, and full async interleaving thread isolation utilizing Dart Zones and Cancellable."
version: 1.0.0

homepage: https://github.com/aymtools/an_reactive_state/
issue_tracker: https://github.com/aymtools/an_reactive_state/issues

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: '>=3.10.0'

dependencies:
  flutter:
    sdk: flutter
  cancellable: ^2.6.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: any

flutter:
